version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: leetcode_db
    environment:
      POSTGRES_DB: leetcode_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5499:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 